package com.example.playpauseexoplayer;

public class Resources {

    public static final VideoModel[] VIDEO_MODELS = {
            new VideoModel(false, 1,
                    "Big Buck Bunny",
                    "Big Buck Bunny tells the story of a giant rabbit with a heart bigger than himself.",
                    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
                    "https://homepages.cae.wisc.edu/~ece533/images/mountain.png"),
            new VideoModel(false, 2,
                    "Elephant Dream",
                    "The first Blender Open Movie from 2006",
                    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
                    "https://homepages.cae.wisc.edu/~ece533/images/cat.png"),
            new VideoModel(false, 3,
                    "We Are Going On Bullrun 1",
                    "Give your opinion about the Ayodhya temple controversy.",
                    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
                    "https://homepages.cae.wisc.edu/~ece533/images/frymire.png"),
            new VideoModel(false, 4,
                    "SubaruOutbackOnStreetAndDirt",
                    "Smoking Tire takes the all-new Subaru Outback to the highest point",
                    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
                    "https://homepages.cae.wisc.edu/~ece533/images/monarch.png"),
            new VideoModel(false, 5,
                    "WeAreGoingOnBullrun 2",
                    "The Smoking Tire",
                    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
                    "https://homepages.cae.wisc.edu/~ece533/images/pool.png"),
            new VideoModel(false, 5,"Intent Extras","Sending Data to a New Activity with Intent Extras",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/Sending+Data+to+a+New+Activity+with+Intent+Extras.mp4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/Sending+Data+to+a+New+Activity+with+Intent+Extras.png"),
            new VideoModel(false, 6,"REST API, Retrofit2, MVVM Course SUMMARY",
                    "Description for media object 2",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/REST+API+Retrofit+MVVM+Course+Summary.mp4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/REST+API%2C+Retrofit2%2C+MVVM+Course+SUMMARY.png"),
            new VideoModel(false, 7,"MVVM and LiveData",
                    "Description for media object 3",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/MVVM+and+LiveData+for+youtube.mp4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/mvvm+and+livedata.png"),
            new VideoModel(false, 8,"Swiping Views with a ViewPager",
                    "Description for media object 4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/SwipingViewPager+Tutorial.mp4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/Swiping+Views+with+a+ViewPager.png"),
            new VideoModel(false, 9,"Database Cache, MVVM, Retrofit, REST API",
                    "Description for media object 5",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/Rest+api+teaser+video.mp4",
                    "https://s3.ca-central-1.amazonaws.com/codingwithmitch/media/VideoPlayerRecyclerView/Rest+API+Integration+with+MVVM.png")
    };
}